/**
 * Bundle the Obsidian plugin to plugin-dist/main.js.
 *
 * The node-builtin guard fails the build if any `node:*` / bare builtin import
 * is reachable from the plugin entry — the mobile-safety gate that keeps the
 * shared core honest.
 */

import { copyFileSync, mkdirSync } from "node:fs";
import process from "node:process";

import builtins from "builtin-modules";
import esbuild from "esbuild";

const watch = process.argv.includes("--watch");
const prod = process.argv.includes("--prod");

/** Copy the canonical manifest + versions next to main.js so plugin-dist/ is a
 * complete, installable plugin folder (and a ready set of release assets). */
function copyMeta() {
  mkdirSync("plugin-dist", { recursive: true });
  copyFileSync("manifest.json", "plugin-dist/manifest.json");
  copyFileSync("versions.json", "plugin-dist/versions.json");
  copyFileSync("styles.css", "plugin-dist/styles.css");
}

const builtinSet = new Set([
  ...builtins,
  ...builtins.map((b) => `node:${b}`),
]);

/** @type {import('esbuild').Plugin} */
const nodeBuiltinGuard = {
  name: "node-builtin-guard",
  setup(build) {
    build.onResolve({ filter: /.*/ }, (args) => {
      if (builtinSet.has(args.path)) {
        return {
          errors: [
            {
              text:
                `Node built-in "${args.path}" is reachable from the plugin ` +
                `bundle (imported by ${args.importer}). The plugin must be ` +
                `node-free to run on mobile — route this through an adapter port.`,
            },
          ],
        };
      }
      return null;
    });
  },
};

const options = {
  entryPoints: ["src/plugin/main.ts"],
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: "es2018",
  // Obsidian + electron + CodeMirror are provided by the host; everything else
  // is bundled (node builtins are caught by the guard, not externalized).
  external: [
    "obsidian",
    "electron",
    "@codemirror/view",
    "@codemirror/state",
    "@codemirror/language",
    "@lezer/common",
  ],
  outfile: "plugin-dist/main.js",
  sourcemap: prod ? false : "inline",
  minify: prod,
  treeShaking: true,
  logLevel: "info",
  banner: {
    js: "/* Confluence Tools — Obsidian plugin (generated by esbuild). */",
  },
  plugins: [nodeBuiltinGuard],
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  copyMeta();
  console.log("esbuild: watching plugin sources…");
} else {
  await esbuild.build(options);
  copyMeta();
  console.log("esbuild: plugin bundled → plugin-dist/{main.js,manifest.json,versions.json}");
}
