name: Release

# This workflow publishes new releases to npm and GitHub using semantic-release.
# It must run from the repository root so that @semantic-release/npm can find package.json.

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write # create tags and GitHub releases
    issues: write # comment on issues
    pull-requests: write

jobs:
    release:
        name: Semantic Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # required for semantic-release to analyze commits

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: npm ci

            # semantic-release runs from the repo root; build is triggered by .releaserc (prepare step)
            - name: Run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release --repository-url "${{ github.server_url }}/${{ github.repository }}.git"

    show-token:
        name: Inspect NPM token (first/last char)
        runs-on: ubuntu-latest
        steps:
            - name: Print first and last character of NPM_TOKEN
              env:
                  TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  if [ -z "$TOKEN" ]; then
                      echo "NPM_TOKEN is empty"; exit 1; fi
                  first_char="${TOKEN:0:1}"
                  last_char="$(printf %s "$TOKEN" | tail -c 1)"
                  echo "First char: $first_char"
                  echo "Last char: $last_char"
